### ISSUE TITLE
Wasted space when not using sidebar

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#105]
**Package version**
0.14.1

**Current behavior (bug description)**
Pages don’t use the full width of the screen because of this rule:

```css
@media (min-width:1280px) {
    .admin-interface.change-list:not(.popup) #main.shifted > .content,
    .admin-interface.change-form:not(.popup) #main.shifted > .content {
        max-width: calc(100% - 360px);
    }
}
```

**Expected behavior**

When `admin.site.enable_nav_sidebar` is false, don’t reserve 360px.
