### ISSUE TITLE
Collapsible filters in admin listings

### ISSUE THREAD

**Issue by morlandi** [fabiocaccamo/django-admin-interface#252]
Sometime you need to display many columns in the listing,
and the horizontal space taken up by the filters results in additional horizontal scrolling which might be inconvenient.

In these situations, the possibility to (optionally) collapse the filters could help; mush like [django-grappelli](https://github.com/sehmaschine/django-grappelli) does:

<img width="568" alt="Screenshot 2023-01-31 at 16 48 45" src="https://user-images.githubusercontent.com/299854/215814698-3e7bf4b0-4168-4f9c-8def-5833a3649bdf.png">

<img width="546" alt="Screenshot 2023-01-31 at 16 46 30" src="https://user-images.githubusercontent.com/299854/215814739-bb659e5f-5938-42ca-bfb2-13f2221b6f71.png">

**Comment by fabiocaccamo** [comment]
@morlandi cool suggestion!

**Comment by smunoz-ml** [comment]
This is similar to what I have suggested in #163!

**Comment by fabiocaccamo** [comment]
@smunoz-ml true, even if at UI level, having the filter collapsible to the right seems to be more complicated than having it in an absolute position above the changelist.

**Comment by morlandi** [comment]
> @smunoz-ml true, even if at UI level, having the filter collapsible to the right seems to be more complicated than having it in an absolute position above the changelist.

I do agree on this point, partly because the django-grappelli solution is familiar to me and therefore I'm used to it, but above all because having the filters under your nose (even when collapsed they act as a placeholder), is more intuitive compared to an anonymous button.

**Comment by merwok** [comment]
Sidebar collapsing would look better and be more usable than the button style in the screenshot!

**Comment by morlandi** [comment]
The real challenge here is to implement this without interfering too much with Django admin templates .. so the solution can survive across future Django releases ;)

I am available to collaborate in the implementation perhaps with some strategic suggestions from the author @fabiocaccamo , or at the very least to test a temporary solution during development

**Comment by fabiocaccamo** [comment]
@morlandi if you want to work on a PR for this, I will be glad to discuss it together.

I would opt for the "Grappelli" solution, it seems to me the better at UX level and also easier to develop/maintain in the long term.

**Comment by fabiocaccamo** [comment]
Some time ago I did some tests, I paste what I did here, so I can delete the file from my desktop :)

```css
/* solution 1 */
  .admin-interface .module.filtered #changelist-filter {
      position: fixed;
      z-index: 50;
      box-shadow: 0px 4px 16px rgba(0,0,0,0.2);
      bottom: 40px;
      right: 40px;
      top: auto;
      max-width: 240px;
      margin: 0;
      padding: 0;
      max-height: calc(100% - 115px);
  }

  .admin-interface .module.filtered #changelist-filter > h2 {
      position: sticky;
      top: 0;
      z-index: 10;
      border: 1px solid rgba(255,255,255,0.3);
      border-bottom: none;
      cursor: pointer;
  }


  /* collapsed */
  .admin-interface .module.filtered #changelist-filter {
      height: 35px;
      overflow: hidden;
  }

/* solution 2 */
  .admin-interface .module.filtered #changelist-filter {
      margin-left: -240px;
      height: 34px;
      overflow: hidden;
      cursor: pointer;
      margin-top: 5px;
      box-shadow: 4px 4px 16px rgba(0,0,0,0.6);
  }

```
